# Generated by Django 3.2.4 on 2021-10-04 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='release',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.release'),
            preserve_default=False,
        ),
    ]
