# Generated by Django 3.2.4 on 2021-10-03 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.release'),
        ),
    ]
