# Generated by Django 3.2.4 on 2021-10-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_article_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='release',
        ),
        migrations.AddField(
            model_name='article',
            name='release',
            field=models.ManyToManyField(to='api.Release'),
        ),
    ]
