# Generated by Django 3.2.4 on 2021-10-04 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211004_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='release',
        ),
        migrations.AddField(
            model_name='release',
            name='article',
            field=models.ForeignKey(default=django.db.models.deletion.SET_NULL, on_delete=django.db.models.deletion.CASCADE, to='api.article'),
        ),
    ]
