# Generated by Django 3.2.4 on 2021-10-04 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211004_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article'),
        ),
    ]
