# Generated by Django 3.2.4 on 2021-10-04 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_release_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='article',
        ),
    ]
